billboardText: "SAKHEE BHURE"  
quoteText: "Love and learning are similar in that they can never be wasted."
quoteAuthor: " - Hope Jahren"
title: Sakhee Bhure
tagline: sakhee.space
twitter:
  username: sakheebhure
url: https://sakhee.space/
sass:
  style: compressed
plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag
